const db = require('./index');
const { Team, Match, Rank } = require('../app/models');

async function connect() {
  db.connect();
}

async function disconnect(done) {
  db.disconnect(done);
}

async function seedTeam() {
  await Team.deleteMany({});

  await Team.create([
    {
      longName: 'SAMPDORIA',
      shortName: 'SAM',
      thumbnail: 'sampdoria.png',
    },
    {
      longName: 'INTERNAZIONALE',
      shortName: 'INT',
      thumbnail: 'inter-de-milao.png',
    },
    {
      longName: 'FIORENTINA',
      shortName: 'FIO',
      thumbnail: 'fiorentina.png',
    },
    {
      longName: 'MILAN',
      shortName: 'MIL',
      thumbnail: 'milan.png',
    },
    {
      longName: 'JUVENTUS',
      shortName: 'JUV',
      thumbnail: 'juventus.png',
    },
    {
      longName: 'NAPOLI',
      shortName: 'NAP',
      thumbnail: 'napoli.png',
    },
    {
      longName: 'SUASSUOLO',
      shortName: 'SUA',
      thumbnail: 'suassuolo.png',
    },
    {
      longName: 'PARMA',
      shortName: 'PAR',
      thumbnail: 'parma.png',
    },
    {
      longName: 'PALERMO',
      shortName: 'PAL',
      thumbnail: 'palermo.png',
    },
    {
      longName: 'ROMA',
      shortName: 'ROM',
      thumbnail: 'roma.png',
    },
  ]);
}

async function seedMatch() {
  await Match.deleteMany({});

  const teams = await Team.find();

  await Match.create([
    {
      category: 'A',
      round: 1,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: 1,
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: 3,
      day: '2020-02-10 21:00:00',
      week: 7,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 1,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: 2,
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: 1,
      day: '2020-02-11 21:00:00',
      week: 7,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 1,
      teamHome: teams.find((team) => team.longName === 'SUASSUOLO')._id,
      scoreHome: 0,
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: 2,
      day: '2020-02-12 21:00:00',
      week: 7,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 1,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: 1,
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: 1,
      day: '2020-02-13 21:00:00',
      week: 7,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 1,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: 5,
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: 1,
      day: '2020-02-17 21:00:00',
      week: 8,
      weekDay: 'SEG',
    },
    // ROUND 2
    {
      category: 'A',
      round: 2,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: 1,
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: 4,
      day: '2020-02-18 21:00:00',
      week: 8,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 2,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: 2,
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: 4,
      day: '2020-02-19 21:00:00',
      week: 8,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 2,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: 3,
      teamAway: teams.find((team) => team.longName === 'SUASSUOLO')._id,
      scoreAway: 3,
      day: '2020-02-20 21:00:00',
      week: 8,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 2,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-03-02 21:00:00',
      week: 10,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 2,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: 4,
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: 4,
      day: '2020-03-03 21:00:00',
      week: 10,
      weekDay: 'TER',
    },
    // ROUND 3
    {
      category: 'A',
      round: 3,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: 3,
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: 3,
      day: '2020-03-04 21:00:00',
      week: 10,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 3,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: 1,
      teamAway: teams.find((team) => team.longName === 'SUASSUOLO')._id,
      scoreAway: 1,
      day: '2020-03-05 21:00:00',
      week: 10,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 3,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: 3,
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: 1,
      day: '2020-03-09 21:00:00',
      week: 11,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 3,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: 1,
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: 3,
      day: '2020-03-10 21:00:00',
      week: 11,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 3,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: 1,
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: 0,
      day: '2020-03-11 21:00:00',
      week: 11,
      weekDay: 'QUA',
    },
    // ROUND 4
    {
      category: 'A',
      round: 4,
      teamHome: teams.find((team) => team.longName === 'SUASSUOLO')._id,
      scoreHome: 4,
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: 3,
      day: '2020-03-12 21:00:00',
      week: 11,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 4,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-03-16 21:00:00',
      week: 12,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 4,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-03-17 21:00:00',
      week: 12,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 4,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-03-18 21:00:00',
      week: 12,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 4,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-03-19 21:00:00',
      week: 12,
      weekDay: 'QUI',
    },
    // ROUND 5
    {
      category: 'A',
      round: 5,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-03-23 21:00:00',
      week: 13,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 5,
      teamHome: teams.find((team) => team.longName === 'SUASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-03-24 21:00:00',
      week: 13,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 5,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-03-25 21:00:00',
      week: 13,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 5,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-03-26 21:00:00',
      week: 13,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 5,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-03-30 21:00:00',
      week: 14,
      weekDay: 'SEG',
    },
  ]);
}

async function seedRank() {
  await Rank.deleteMany({});

  const teams = await Team.find();

  await Rank.create([
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      points: 0,
      played: 2,
      wons: 0,
      drawn: 0,
      lost: 2,
      goalDifference: -2,
    },
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      points: 1,
      played: 4,
      wons: 0,
      drawn: 1,
      lost: 3,
      goalDifference: -5,
    },
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'FIORENTINA')._id,
      points: 4,
      played: 3,
      wons: 1,
      drawn: 1,
      lost: 1,
      goalDifference: -3,
    },
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'MILAN')._id,
      points: 3,
      played: 2,
      wons: 1,
      drawn: 0,
      lost: 1,
      goalDifference: 2,
    },
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'JUVENTUS')._id,
      points: 3,
      played: 3,
      wons: 1,
      drawn: 0,
      lost: 2,
      goalDifference: -4,
    },
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'NAPOLI')._id,
      points: 7,
      played: 3,
      wons: 2,
      drawn: 1,
      lost: 0,
      goalDifference: 4,
    },
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'SUASSUOLO')._id,
      points: 5,
      played: 4,
      wons: 1,
      drawn: 2,
      lost: 1,
      goalDifference: -1,
    },
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'PARMA')._id,
      points: 7,
      played: 3,
      wons: 2,
      drawn: 1,
      lost: 0,
      goalDifference: 5,
    },
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'PALERMO')._id,
      points: 5,
      played: 3,
      wons: 1,
      drawn: 2,
      lost: 0,
      goalDifference: 2,
    },
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'ROMA')._id,
      points: 5,
      played: 3,
      wons: 1,
      drawn: 2,
      lost: 0,
      goalDifference: 2,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      points: 30,
      played: 5,
      wons: 10,
      drawn: 1,
      lost: 0,
      goalDifference: 20,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      points: 25,
      played: 5,
      wons: 10,
      drawn: 1,
      lost: 0,
      goalDifference: 20,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'FIORENTINA')._id,
      points: 6,
      played: 5,
      wons: 10,
      drawn: 1,
      lost: 0,
      goalDifference: 20,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'MILAN')._id,
      points: 15,
      played: 5,
      wons: 10,
      drawn: 1,
      lost: 0,
      goalDifference: 20,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'JUVENTUS')._id,
      points: 5,
      played: 5,
      wons: 10,
      drawn: 1,
      lost: 0,
      goalDifference: 20,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'NAPOLI')._id,
      points: 20,
      played: 5,
      wons: 10,
      drawn: 1,
      lost: 0,
      goalDifference: 10,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'SUASSUOLO')._id,
      points: 35,
      played: 5,
      wons: 10,
      drawn: 1,
      lost: 0,
      goalDifference: 15,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'PARMA')._id,
      points: 8,
      played: 5,
      wons: 10,
      drawn: 1,
      lost: 0,
      goalDifference: 20,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'PALERMO')._id,
      points: 6,
      played: 5,
      wons: 10,
      drawn: 1,
      lost: 0,
      goalDifference: 20,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'ROMA')._id,
      points: 4,
      played: 5,
      wons: 10,
      drawn: 1,
      lost: 0,
      goalDifference: 20,
    },
  ]);
}

async function seed() {
  await connect();

  await seedTeam();
  await seedMatch();
  await seedRank();

  await disconnect();
}

seed();
