const db = require('./index');
const { Team, Match, Rank } = require('../app/models');

async function connect() {
  db.connect();
}

async function disconnect(done) {
  db.disconnect(done);
}

async function seedTeam() {
  await Team.deleteMany({});

  await Team.create([
    {
      longName: 'SAMPDORIA',
      shortName: 'SAM',
      thumbnail: 'sampdoria.png',
    },
    {
      longName: 'INTERNAZIONALE',
      shortName: 'INT',
      thumbnail: 'inter-de-milao.png',
    },
    {
      longName: 'FIORENTINA',
      shortName: 'FIO',
      thumbnail: 'fiorentina.png',
    },
    {
      longName: 'MILAN',
      shortName: 'MIL',
      thumbnail: 'milan.png',
    },
    {
      longName: 'JUVENTUS',
      shortName: 'JUV',
      thumbnail: 'juventus.png',
    },
    {
      longName: 'NAPOLI',
      shortName: 'NAP',
      thumbnail: 'napoli.png',
    },
    {
      longName: 'SASSUOLO',
      shortName: 'SAS',
      thumbnail: 'sassuolo.png',
    },
    {
      longName: 'PARMA',
      shortName: 'PAR',
      thumbnail: 'parma.png',
    },
    {
      longName: 'PALERMO',
      shortName: 'PAL',
      thumbnail: 'palermo.png',
    },
    {
      longName: 'ROMA',
      shortName: 'ROM',
      thumbnail: 'roma.png',
    },
  ]);
}

async function seedMatch() {
  await Match.deleteMany({});

  const teams = await Team.find();

  await Match.create([
    {
      category: 'A',
      round: 1,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: 1,
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: 3,
      day: '2020-02-10 21:00:00',
      week: 7,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 1,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: 2,
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: 1,
      day: '2020-02-11 21:00:00',
      week: 7,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 1,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: 0,
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: 2,
      day: '2020-02-12 21:00:00',
      week: 7,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 1,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: 1,
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: 1,
      day: '2020-02-13 21:00:00',
      week: 7,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 1,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: 5,
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: 1,
      day: '2020-02-17 21:00:00',
      week: 8,
      weekDay: 'SEG',
    },
    // ROUND 2
    {
      category: 'A',
      round: 2,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: 1,
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: 4,
      day: '2020-02-18 21:00:00',
      week: 8,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 2,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: 2,
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: 4,
      day: '2020-02-19 21:00:00',
      week: 8,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 2,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: 3,
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: 3,
      day: '2020-02-20 21:00:00',
      week: 8,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 2,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-03-02 21:00:00',
      week: 10,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 2,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: 4,
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: 4,
      day: '2020-03-03 21:00:00',
      week: 10,
      weekDay: 'TER',
    },
    // ROUND 3
    {
      category: 'A',
      round: 3,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: 3,
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: 3,
      day: '2020-03-04 21:00:00',
      week: 10,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 3,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: 1,
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: 1,
      day: '2020-03-05 21:00:00',
      week: 10,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 3,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: 3,
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: 1,
      day: '2020-03-09 21:00:00',
      week: 11,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 3,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: 1,
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: 3,
      day: '2020-03-10 21:00:00',
      week: 11,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 3,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: 1,
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: 0,
      day: '2020-03-11 21:00:00',
      week: 11,
      weekDay: 'QUA',
    },
    // ROUND 4
    {
      category: 'A',
      round: 4,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: 4,
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: 3,
      day: '2020-03-12 21:00:00',
      week: 11,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 4,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-03-16 21:00:00',
      week: 12,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 4,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-03-17 21:00:00',
      week: 12,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 4,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-03-18 21:00:00',
      week: 12,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 4,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-03-19 21:00:00',
      week: 12,
      weekDay: 'QUI',
    },
    // ROUND 5
    {
      category: 'A',
      round: 5,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-03-23 21:00:00',
      week: 13,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 5,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-03-24 21:00:00',
      week: 13,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 5,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-03-25 21:00:00',
      week: 13,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 5,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-03-26 21:00:00',
      week: 13,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 5,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-03-30 21:00:00',
      week: 14,
      weekDay: 'SEG',
    },
    // ROUND 6
    {
      category: 'A',
      round: 6,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-03-31 21:00:00',
      week: 14,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 6,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-04-01 21:00:00',
      week: 14,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 6,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-04-02 21:00:00',
      week: 14,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 6,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-04-06 21:00:00',
      week: 15,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 6,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-04-07 21:00:00',
      week: 15,
      weekDay: 'TER',
    },
    // ROUND 7
    {
      category: 'A',
      round: 7,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-04-08 21:00:00',
      week: 15,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 7,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-04-09 21:00:00',
      week: 15,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 7,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-04-13 21:00:00',
      week: 16,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 7,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-04-14 21:00:00',
      week: 16,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 7,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-04-15 21:00:00',
      week: 16,
      weekDay: 'QUA',
    },
    // ROUND 8
    {
      category: 'A',
      round: 8,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-04-16 21:00:00',
      week: 16,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 8,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-04-27 21:00:00',
      week: 18,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 8,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-04-28 21:00:00',
      week: 18,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 8,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-04-29 21:00:00',
      week: 18,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 8,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-04-30 21:00:00',
      week: 18,
      weekDay: 'QUI',
    },
    // ROUND 9
    {
      category: 'A',
      round: 9,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-05-04 21:00:00',
      week: 19,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 9,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-05-05 21:00:00',
      week: 19,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 9,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-05-06 21:00:00',
      week: 19,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 9,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-05-07 21:00:00',
      week: 19,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 9,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-05-11 21:00:00',
      week: 20,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 10,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-05-12 21:00:00',
      week: 20,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 10,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-05-13 21:00:00',
      week: 20,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 10,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-05-14 21:00:00',
      week: 20,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 10,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-05-18 21:00:00',
      week: 21,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 10,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-05-19 21:00:00',
      week: 21,
      weekDay: 'TER',
    },
    // ROUND 11
    {
      category: 'A',
      round: 11,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-05-20 21:00:00',
      week: 21,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 11,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-05-21 21:00:00',
      week: 21,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 11,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-05-25 21:00:00',
      week: 22,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 11,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-05-26 21:00:00',
      week: 22,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 11,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-05-27 21:00:00',
      week: 22,
      weekDay: 'QUA',
    },
    // ROUND 12
    {
      category: 'A',
      round: 12,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-05-28 21:00:00',
      week: 22,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 12,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-06-01 21:00:00',
      week: 23,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 12,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-06-02 21:00:00',
      week: 23,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 12,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-06-03 21:00:00',
      week: 23,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 12,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-06-04 21:00:00',
      week: 23,
      weekDay: 'QUI',
    },
    // ROUND 13
    {
      category: 'A',
      round: 13,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-06-08 21:00:00',
      week: 24,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 13,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-06-09 21:00:00',
      week: 24,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 13,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-06-10 21:00:00',
      week: 24,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 13,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-06-15 21:00:00',
      week: 25,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 13,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-06-16 21:00:00',
      week: 25,
      weekDay: 'TER',
    },
    // ROUND 14
    {
      category: 'A',
      round: 14,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-06-17 21:00:00',
      week: 25,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 14,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-06-18 21:00:00',
      week: 25,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 14,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-06-22 21:00:00',
      week: 26,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 14,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-06-23 21:00:00',
      week: 26,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 14,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-06-24 21:00:00',
      week: 26,
      weekDay: 'QUA',
    },
    // ROUND 15
    {
      category: 'A',
      round: 15,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-06-25 21:00:00',
      week: 26,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 15,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-06-29 21:00:00',
      week: 27,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 15,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-06-30 21:00:00',
      week: 27,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 15,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-07-01 21:00:00',
      week: 27,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 15,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-07-02 21:00:00',
      week: 27,
      weekDay: 'QUI',
    },
    // ROUND 16
    {
      category: 'A',
      round: 16,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-07-06 21:00:00',
      week: 28,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 16,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-07-07 21:00:00',
      week: 28,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 16,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-07-08 21:00:00',
      week: 28,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 16,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-07-09 21:00:00',
      week: 28,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 16,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-07-13 21:00:00',
      week: 29,
      weekDay: 'SEG',
    },
    // ROUND 17
    {
      category: 'A',
      round: 17,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-07-14 21:00:00',
      week: 29,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 17,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-07-15 21:00:00',
      week: 29,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 17,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-07-16 21:00:00',
      week: 29,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 17,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-08-03 21:00:00',
      week: 32,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 17,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-08-04 21:00:00',
      week: 32,
      weekDay: 'TER',
    },
    // ROUND 18
    {
      category: 'A',
      round: 18,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-08-05 21:00:00',
      week: 32,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 18,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-08-06 21:00:00',
      week: 32,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 18,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-08-10 21:00:00',
      week: 33,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 18,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-08-11 21:00:00',
      week: 33,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 18,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-08-12 21:00:00',
      week: 33,
      weekDay: 'QUA',
    },
    // ROUND 19
    {
      category: 'A',
      round: 19,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-08-13 21:00:00',
      week: 33,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 19,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-08-17 21:00:00',
      week: 34,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 19,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-08-18 21:00:00',
      week: 34,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 19,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-08-19 21:00:00',
      week: 34,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 19,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-08-20 21:00:00',
      week: 34,
      weekDay: 'QUI',
    },
    // ROUND 20
    {
      category: 'A',
      round: 20,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-08-24 21:00:00',
      week: 35,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 20,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-08-25 21:00:00',
      week: 35,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 20,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-08-26 21:00:00',
      week: 35,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 20,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-08-27 21:00:00',
      week: 35,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 20,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: 4,
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: 4,
      day: '2020-08-31 21:00:00',
      week: 36,
      weekDay: 'SEG',
    },
    // ROUND 21
    {
      category: 'A',
      round: 21,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-09-01 21:00:00',
      week: 36,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 21,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-09-02 21:00:00',
      week: 36,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 21,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-09-03 21:00:00',
      week: 36,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 21,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-09-08 21:00:00',
      week: 37,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 21,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-09-09 21:00:00',
      week: 37,
      weekDay: 'QUA',
    },
    // ROUND 22
    {
      category: 'A',
      round: 22,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-09-10 21:00:00',
      week: 37,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 22,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-09-14 21:00:00',
      week: 38,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 22,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-09-15 21:00:00',
      week: 38,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 22,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-09-16 21:00:00',
      week: 38,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 22,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-09-17 21:00:00',
      week: 38,
      weekDay: 'QUI',
    },
    // ROUND 23
    {
      category: 'A',
      round: 23,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-09-21 21:00:00',
      week: 39,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 23,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-09-22 21:00:00',
      week: 39,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 23,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-09-23 21:00:00',
      week: 39,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 23,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-09-24 21:00:00',
      week: 39,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 23,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-09-28 21:00:00',
      week: 40,
      weekDay: 'SEG',
    },
    // ROUND 24
    {
      category: 'A',
      round: 24,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-09-29 21:00:00',
      week: 40,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 24,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-09-30 21:00:00',
      week: 40,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 24,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-10-01 21:00:00',
      week: 40,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 24,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-10-05 21:00:00',
      week: 41,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 24,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-10-06 21:00:00',
      week: 41,
      weekDay: 'TER',
    },
    // ROUND 25
    {
      category: 'A',
      round: 25,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-10-07 21:00:00',
      week: 41,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 25,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-10-08 21:00:00',
      week: 41,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 25,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-10-13 21:00:00',
      week: 42,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 25,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-10-14 21:00:00',
      week: 42,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 25,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-10-15 21:00:00',
      week: 42,
      weekDay: 'QUI',
    },
    // ROUND 26
    {
      category: 'A',
      round: 26,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-10-19 21:00:00',
      week: 43,
      weekDay: 'SEG',
    },
    {
      category: 'A',
      round: 26,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-10-20 21:00:00',
      week: 43,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 26,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-10-21 21:00:00',
      week: 43,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 26,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-10-22 21:00:00',
      week: 43,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 26,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-10-26 21:00:00',
      week: 44,
      weekDay: 'SEG',
    },
    // ROUND 27
    {
      category: 'A',
      round: 27,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-10-27 21:00:00',
      week: 44,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 27,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-10-28 21:00:00',
      week: 44,
      weekDay: 'QUA',
    },
    {
      category: 'A',
      round: 27,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-10-29 21:00:00',
      week: 44,
      weekDay: 'QUI',
    },
    {
      category: 'A',
      round: 27,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-11-03 21:00:00',
      week: 45,
      weekDay: 'TER',
    },
    {
      category: 'A',
      round: 27,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-11-04 21:00:00',
      week: 45,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 1,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: 1,
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: 3,
      day: '2020-02-10 21:00:00',
      week: 7,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 1,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: 3,
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: 2,
      day: '2020-02-11 21:00:00',
      week: 7,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 1,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: 3,
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: 1,
      day: '2020-02-12 21:00:00',
      week: 7,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 1,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: 2,
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: 1,
      day: '2020-02-13 21:00:00',
      week: 7,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 1,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: 0,
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: 0,
      day: '2020-02-17 21:00:00',
      week: 8,
      weekDay: 'SEG',
    },
    // ROUND 2
    {
      category: 'B',
      round: 2,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: 1,
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: 2,
      day: '2020-02-18 21:00:00',
      week: 8,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 2,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: 1,
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: 1,
      day: '2020-02-19 21:00:00',
      week: 8,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 2,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: 2,
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: 0,
      day: '2020-02-20 21:00:00',
      week: 8,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 2,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-03-02 21:00:00',
      week: 10,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 2,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: 2,
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: 2,
      day: '2020-03-03 21:00:00',
      week: 10,
      weekDay: 'TER',
    },
    // ROUND 3
    {
      category: 'B',
      round: 3,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: 3,
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: 3,
      day: '2020-03-04 21:00:00',
      week: 10,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 3,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: 2,
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: 5,
      day: '2020-03-05 21:00:00',
      week: 10,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 3,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: 2,
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: 0,
      day: '2020-03-09 21:00:00',
      week: 11,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 3,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: 2,
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: 3,
      day: '2020-03-10 21:00:00',
      week: 11,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 3,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: 1,
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: 0,
      day: '2020-03-11 21:00:00',
      week: 11,
      weekDay: 'QUA',
    },
    // ROUND 4
    {
      category: 'B',
      round: 4,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: 1,
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: 1,
      day: '2020-03-12 21:00:00',
      week: 11,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 4,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-03-16 21:00:00',
      week: 12,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 4,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-03-17 21:00:00',
      week: 12,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 4,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-03-18 21:00:00',
      week: 12,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 4,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-03-19 21:00:00',
      week: 12,
      weekDay: 'QUI',
    },
    // ROUND 5
    {
      category: 'B',
      round: 5,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-03-23 21:00:00',
      week: 13,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 5,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-03-24 21:00:00',
      week: 13,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 5,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-03-25 21:00:00',
      week: 13,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 5,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-03-26 21:00:00',
      week: 13,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 5,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-03-30 21:00:00',
      week: 14,
      weekDay: 'SEG',
    },
    // ROUND 6
    {
      category: 'B',
      round: 6,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-03-31 21:00:00',
      week: 14,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 6,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-04-01 21:00:00',
      week: 14,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 6,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-04-02 21:00:00',
      week: 14,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 6,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-04-06 21:00:00',
      week: 15,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 6,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-04-07 21:00:00',
      week: 15,
      weekDay: 'TER',
    },
    // ROUND 7
    {
      category: 'B',
      round: 7,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-04-08 21:00:00',
      week: 15,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 7,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-04-09 21:00:00',
      week: 15,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 7,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-04-13 21:00:00',
      week: 16,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 7,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-04-14 21:00:00',
      week: 16,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 7,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-04-15 21:00:00',
      week: 16,
      weekDay: 'QUA',
    },
    // ROUND 8
    {
      category: 'B',
      round: 8,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-04-16 21:00:00',
      week: 16,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 8,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-04-27 21:00:00',
      week: 18,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 8,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-04-28 21:00:00',
      week: 18,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 8,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-04-29 21:00:00',
      week: 18,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 8,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-04-30 21:00:00',
      week: 18,
      weekDay: 'QUI',
    },
    // ROUND 9
    {
      category: 'B',
      round: 9,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-05-04 21:00:00',
      week: 19,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 9,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-05-05 21:00:00',
      week: 19,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 9,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-05-06 21:00:00',
      week: 19,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 9,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-05-07 21:00:00',
      week: 19,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 9,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-05-11 21:00:00',
      week: 20,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 10,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-05-12 21:00:00',
      week: 20,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 10,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-05-13 21:00:00',
      week: 20,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 10,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-05-14 21:00:00',
      week: 20,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 10,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-05-18 21:00:00',
      week: 21,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 10,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-05-19 21:00:00',
      week: 21,
      weekDay: 'TER',
    },
    // ROUND 11
    {
      category: 'B',
      round: 11,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-05-20 21:00:00',
      week: 21,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 11,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-05-21 21:00:00',
      week: 21,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 11,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-05-25 21:00:00',
      week: 22,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 11,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-05-26 21:00:00',
      week: 22,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 11,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-05-27 21:00:00',
      week: 22,
      weekDay: 'QUA',
    },
    // ROUND 12
    {
      category: 'B',
      round: 12,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-05-28 21:00:00',
      week: 22,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 12,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-06-01 21:00:00',
      week: 23,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 12,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-06-02 21:00:00',
      week: 23,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 12,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-06-03 21:00:00',
      week: 23,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 12,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-06-04 21:00:00',
      week: 23,
      weekDay: 'QUI',
    },
    // ROUND 13
    {
      category: 'B',
      round: 13,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-06-08 21:00:00',
      week: 24,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 13,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-06-09 21:00:00',
      week: 24,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 13,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-06-10 21:00:00',
      week: 24,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 13,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-06-15 21:00:00',
      week: 25,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 13,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-06-16 21:00:00',
      week: 25,
      weekDay: 'TER',
    },
    // ROUND 14
    {
      category: 'B',
      round: 14,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-06-17 21:00:00',
      week: 25,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 14,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-06-18 21:00:00',
      week: 25,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 14,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-06-22 21:00:00',
      week: 26,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 14,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-06-23 21:00:00',
      week: 26,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 14,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-06-24 21:00:00',
      week: 26,
      weekDay: 'QUA',
    },
    // ROUND 15
    {
      category: 'B',
      round: 15,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-06-25 21:00:00',
      week: 26,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 15,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-06-29 21:00:00',
      week: 27,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 15,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-06-30 21:00:00',
      week: 27,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 15,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-07-01 21:00:00',
      week: 27,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 15,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-07-02 21:00:00',
      week: 27,
      weekDay: 'QUI',
    },
    // ROUND 16
    {
      category: 'B',
      round: 16,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-07-06 21:00:00',
      week: 28,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 16,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-07-07 21:00:00',
      week: 28,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 16,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-07-08 21:00:00',
      week: 28,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 16,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-07-09 21:00:00',
      week: 28,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 16,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-07-13 21:00:00',
      week: 29,
      weekDay: 'SEG',
    },
    // ROUND 17
    {
      category: 'B',
      round: 17,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-07-14 21:00:00',
      week: 29,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 17,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-07-15 21:00:00',
      week: 29,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 17,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-07-16 21:00:00',
      week: 29,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 17,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-08-03 21:00:00',
      week: 32,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 17,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-08-04 21:00:00',
      week: 32,
      weekDay: 'TER',
    },
    // ROUND 18
    {
      category: 'B',
      round: 18,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-08-05 21:00:00',
      week: 32,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 18,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-08-06 21:00:00',
      week: 32,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 18,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-08-10 21:00:00',
      week: 33,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 18,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-08-11 21:00:00',
      week: 33,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 18,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-08-12 21:00:00',
      week: 33,
      weekDay: 'QUA',
    },
    // ROUND 19
    {
      category: 'B',
      round: 19,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-08-13 21:00:00',
      week: 33,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 19,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-08-17 21:00:00',
      week: 34,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 19,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-08-18 21:00:00',
      week: 34,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 19,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-08-19 21:00:00',
      week: 34,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 19,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-08-20 21:00:00',
      week: 34,
      weekDay: 'QUI',
    },
    // ROUND 20
    {
      category: 'B',
      round: 20,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-08-24 21:00:00',
      week: 35,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 20,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-08-25 21:00:00',
      week: 35,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 20,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-08-26 21:00:00',
      week: 35,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 20,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-08-27 21:00:00',
      week: 35,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 20,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: 4,
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: 4,
      day: '2020-08-31 21:00:00',
      week: 36,
      weekDay: 'SEG',
    },
    // ROUND 21
    {
      category: 'B',
      round: 21,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-09-01 21:00:00',
      week: 36,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 21,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-09-02 21:00:00',
      week: 36,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 21,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-09-03 21:00:00',
      week: 36,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 21,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-09-08 21:00:00',
      week: 37,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 21,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-09-09 21:00:00',
      week: 37,
      weekDay: 'QUA',
    },
    // ROUND 22
    {
      category: 'B',
      round: 22,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-09-10 21:00:00',
      week: 37,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 22,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-09-14 21:00:00',
      week: 38,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 22,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-09-15 21:00:00',
      week: 38,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 22,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-09-16 21:00:00',
      week: 38,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 22,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-09-17 21:00:00',
      week: 38,
      weekDay: 'QUI',
    },
    // ROUND 23
    {
      category: 'B',
      round: 23,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-09-21 21:00:00',
      week: 39,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 23,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-09-22 21:00:00',
      week: 39,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 23,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-09-23 21:00:00',
      week: 39,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 23,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-09-24 21:00:00',
      week: 39,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 23,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-09-28 21:00:00',
      week: 40,
      weekDay: 'SEG',
    },
    // ROUND 24
    {
      category: 'B',
      round: 24,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-09-29 21:00:00',
      week: 40,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 24,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-09-30 21:00:00',
      week: 40,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 24,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-10-01 21:00:00',
      week: 40,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 24,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-10-05 21:00:00',
      week: 41,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 24,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-10-06 21:00:00',
      week: 41,
      weekDay: 'TER',
    },
    // ROUND 25
    {
      category: 'B',
      round: 25,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-10-07 21:00:00',
      week: 41,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 25,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-10-08 21:00:00',
      week: 41,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 25,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'ROMA')._id,
      scoreAway: '',
      day: '2020-10-13 21:00:00',
      week: 42,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 25,
      teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'MILAN')._id,
      scoreAway: '',
      day: '2020-10-14 21:00:00',
      week: 42,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 25,
      teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-10-15 21:00:00',
      week: 42,
      weekDay: 'QUI',
    },
    // ROUND 26
    {
      category: 'B',
      round: 26,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreAway: '',
      day: '2020-10-19 21:00:00',
      week: 43,
      weekDay: 'SEG',
    },
    {
      category: 'B',
      round: 26,
      teamHome: teams.find((team) => team.longName === 'PARMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreAway: '',
      day: '2020-10-20 21:00:00',
      week: 43,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 26,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-10-21 21:00:00',
      week: 43,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 26,
      teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-10-22 21:00:00',
      week: 43,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 26,
      teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreAway: '',
      day: '2020-10-26 21:00:00',
      week: 44,
      weekDay: 'SEG',
    },
    // ROUND 27
    {
      category: 'B',
      round: 27,
      teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
      scoreAway: '',
      day: '2020-10-27 21:00:00',
      week: 44,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 27,
      teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PARMA')._id,
      scoreAway: '',
      day: '2020-10-28 21:00:00',
      week: 44,
      weekDay: 'QUA',
    },
    {
      category: 'B',
      round: 27,
      teamHome: teams.find((team) => team.longName === 'MILAN')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
      scoreAway: '',
      day: '2020-10-29 21:00:00',
      week: 44,
      weekDay: 'QUI',
    },
    {
      category: 'B',
      round: 27,
      teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      scoreAway: '',
      day: '2020-11-03 21:00:00',
      week: 45,
      weekDay: 'TER',
    },
    {
      category: 'B',
      round: 27,
      teamHome: teams.find((team) => team.longName === 'ROMA')._id,
      scoreHome: '',
      teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
      scoreAway: '',
      day: '2020-11-04 21:00:00',
      week: 45,
      weekDay: 'QUA',
    },
  ]);
}

async function seedRank() {
  await Rank.deleteMany({});

  const teams = await Team.find();

  await Rank.create([
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      points: 0,
      played: 2,
      wons: 0,
      drawn: 0,
      lost: 2,
      goalsFor: 1,
      goalsAgainst: 3,
      goalDifference: -2,
    },
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      points: 1,
      played: 4,
      wons: 0,
      drawn: 1,
      lost: 3,
      goalsFor: 9,
      goalsAgainst: 14,
      goalDifference: -5,
    },
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'FIORENTINA')._id,
      points: 4,
      played: 3,
      wons: 1,
      drawn: 1,
      lost: 1,
      goalsFor: 6,
      goalsAgainst: 9,
      goalDifference: -3,
    },
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'MILAN')._id,
      points: 3,
      played: 2,
      wons: 1,
      drawn: 0,
      lost: 1,
      goalsFor: 6,
      goalsAgainst: 4,
      goalDifference: 2,
    },
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'JUVENTUS')._id,
      points: 3,
      played: 3,
      wons: 1,
      drawn: 0,
      lost: 2,
      goalsFor: 4,
      goalsAgainst: 8,
      goalDifference: -4,
    },
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'NAPOLI')._id,
      points: 7,
      played: 3,
      wons: 2,
      drawn: 1,
      lost: 0,
      goalsFor: 9,
      goalsAgainst: 5,
      goalDifference: 4,
    },
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'SASSUOLO')._id,
      points: 5,
      played: 4,
      wons: 1,
      drawn: 2,
      lost: 1,
      goalsFor: 8,
      goalsAgainst: 9,
      goalDifference: -1,
    },
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'PARMA')._id,
      points: 7,
      played: 3,
      wons: 2,
      drawn: 1,
      lost: 0,
      goalsFor: 9,
      goalsAgainst: 4,
      goalDifference: 5,
    },
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'PALERMO')._id,
      points: 5,
      played: 3,
      wons: 1,
      drawn: 2,
      lost: 0,
      goalsFor: 8,
      goalsAgainst: 6,
      goalDifference: 2,
    },
    {
      category: 'A',
      team: teams.find((team) => team.longName === 'ROMA')._id,
      points: 5,
      played: 3,
      wons: 1,
      drawn: 2,
      lost: 0,
      goalsFor: 6,
      goalsAgainst: 4,
      goalDifference: 2,
    },
    /**
     * Category B
     */
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'SAMPDORIA')._id,
      points: 0,
      played: 2,
      wons: 0,
      drawn: 0,
      lost: 2,
      goalsFor: 2,
      goalsAgainst: 4,
      goalDifference: -2,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
      points: 3,
      played: 4,
      wons: 0,
      drawn: 3,
      lost: 1,
      goalsFor: 6,
      goalsAgainst: 8,
      goalDifference: -2,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'FIORENTINA')._id,
      points: 5,
      played: 3,
      wons: 1,
      drawn: 2,
      lost: 0,
      goalsFor: 3,
      goalsAgainst: 2,
      goalDifference: 1,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'MILAN')._id,
      points: 2,
      played: 2,
      wons: 0,
      drawn: 2,
      lost: 0,
      goalsFor: 2,
      goalsAgainst: 2,
      goalDifference: 0,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'JUVENTUS')._id,
      points: 3,
      played: 3,
      wons: 1,
      drawn: 0,
      lost: 2,
      goalsFor: 4,
      goalsAgainst: 6,
      goalDifference: -2,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'NAPOLI')._id,
      points: 7,
      played: 3,
      wons: 2,
      drawn: 1,
      lost: 0,
      goalsFor: 7,
      goalsAgainst: 3,
      goalDifference: 4,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'SASSUOLO')._id,
      points: 7,
      played: 4,
      wons: 2,
      drawn: 1,
      lost: 1,
      goalsFor: 9,
      goalsAgainst: 6,
      goalDifference: 3,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'PARMA')._id,
      points: 4,
      played: 3,
      wons: 1,
      drawn: 1,
      lost: 1,
      goalsFor: 6,
      goalsAgainst: 7,
      goalDifference: -1,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'PALERMO')._id,
      points: 4,
      played: 3,
      wons: 1,
      drawn: 1,
      lost: 1,
      goalsFor: 5,
      goalsAgainst: 4,
      goalDifference: 1,
    },
    {
      category: 'B',
      team: teams.find((team) => team.longName === 'ROMA')._id,
      points: 4,
      played: 3,
      wons: 1,
      drawn: 1,
      lost: 1,
      goalsFor: 5,
      goalsAgainst: 7,
      goalDifference: -2,
    },
  ]);
}

async function seed() {
  await connect();

  await seedTeam();
  await seedMatch();
  await seedRank();

  await disconnect();
}

seed();
