
// ROUND 19
{
  category: 'A',
  round: 19,
  teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
  scoreAway: '',
  day: '2020-02-10 21:00:00',
  week: 7,
  weekDay: 'SEG',
},
{
  category: 'A',
  round: 19,
  teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
  scoreAway: '',
  day: '2020-02-11 21:00:00',
  week: 7,
  weekDay: 'TER',
},
{
  category: 'A',
  round: 19,
  teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'PARMA')._id,
  scoreAway: '',
  day: '2020-02-12 21:00:00',
  week: 7,
  weekDay: 'QUA',
},
{
  category: 'A',
  round: 19,
  teamHome: teams.find((team) => team.longName === 'ROMA')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
  scoreAway: '',
  day: '2020-02-13 21:00:00',
  week: 7,
  weekDay: 'QUI',
},
{
  category: 'A',
  round: 19,
  teamHome: teams.find((team) => team.longName === 'MILAN')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
  scoreAway: '',
  day: '2020-02-17 21:00:00',
  week: 8,
  weekDay: 'SEG',
},
// ROUND 20
{
  category: 'A',
  round: 20,
  teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'PARMA')._id,
  scoreAway: '',
  day: '2020-02-18 21:00:00',
  week: 8,
  weekDay: 'TER',
},
{
  category: 'A',
  round: 20,
  teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'ROMA')._id,
  scoreAway: '',
  day: '2020-02-19 21:00:00',
  week: 8,
  weekDay: 'QUA',
},
{
  category: 'A',
  round: 20,
  teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
  scoreAway: '',
  day: '2020-02-20 21:00:00',
  week: 8,
  weekDay: 'QUI',
},
{
  category: 'A',
  round: 20,
  teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'MILAN')._id,
  scoreAway: '',
  day: '2020-03-02 21:00:00',
  week: 10,
  weekDay: 'SEG',
},
{
  category: 'A',
  round: 20,
  teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
  scoreHome: 4,
  teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
  scoreAway: 4,
  day: '2020-03-03 21:00:00',
  week: 10,
  weekDay: 'TER',
},
// ROUND 21
{
  category: 'A',
  round: 21,
  teamHome: teams.find((team) => team.longName === 'PARMA')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
  scoreAway: '',
  day: '2020-03-04 21:00:00',
  week: 10,
  weekDay: 'QUA',
},
{
  category: 'A',
  round: 21,
  teamHome: teams.find((team) => team.longName === 'ROMA')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
  scoreAway: '',
  day: '2020-03-05 21:00:00',
  week: 10,
  weekDay: 'QUI',
},
{
  category: 'A',
  round: 21,
  teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
  scoreAway: '',
  day: '2020-03-09 21:00:00',
  week: 11,
  weekDay: 'SEG',
},
{
  category: 'A',
  round: 21,
  teamHome: teams.find((team) => team.longName === 'MILAN')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
  scoreAway: '',
  day: '2020-03-10 21:00:00',
  week: 11,
  weekDay: 'TER',
},
{
  category: 'A',
  round: 21,
  teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
  scoreAway: '',
  day: '2020-03-11 21:00:00',
  week: 11,
  weekDay: 'QUA',
},
// ROUND 22
{
  category: 'A',
  round: 22,
  teamHome: teams.find((team) => team.longName === 'PARMA')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
  scoreAway: '',
  day: '2020-03-04 21:00:00',
  week: 10,
  weekDay: 'QUA',
},
{
  category: 'A',
  round: 22,
  teamHome: teams.find((team) => team.longName === 'ROMA')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
  scoreAway: '',
  day: '2020-03-05 21:00:00',
  week: 10,
  weekDay: 'QUI',
},
{
  category: 'A',
  round: 22,
  teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
  scoreAway: '',
  day: '2020-03-09 21:00:00',
  week: 11,
  weekDay: 'SEG',
},
{
  category: 'A',
  round: 22,
  teamHome: teams.find((team) => team.longName === 'MILAN')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
  scoreAway: '',
  day: '2020-03-10 21:00:00',
  week: 11,
  weekDay: 'TER',
},
{
  category: 'A',
  round: 22,
  teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
  scoreAway: '',
  day: '2020-03-11 21:00:00',
  week: 11,
  weekDay: 'QUA',
},
// ROUND 23
{
  category: 'A',
  round: 23,
  teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
  scoreAway: '',
  day: '2020-03-12 21:00:00',
  week: 11,
  weekDay: 'QUI',
},
{
  category: 'A',
  round: 23,
  teamHome: teams.find((team) => team.longName === 'PARMA')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'NAPOLI')._id,
  scoreAway: '',
  day: '2020-03-16 21:00:00',
  week: 12,
  weekDay: 'SEG',
},
{
  category: 'A',
  round: 23,
  teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'ROMA')._id,
  scoreAway: '',
  day: '2020-03-17 21:00:00',
  week: 12,
  weekDay: 'TER',
},
{
  category: 'A',
  round: 23,
  teamHome: teams.find((team) => team.longName === 'MILAN')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
  scoreAway: '',
  day: '2020-03-18 21:00:00',
  week: 12,
  weekDay: 'QUA',
},
{
  category: 'A',
  round: 23,
  teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
  scoreAway: '',
  day: '2020-03-19 21:00:00',
  week: 12,
  weekDay: 'QUI',
},
// ROUND 24
{
  category: 'A',
  round: 24,
  teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
  scoreAway: '',
  day: '2020-03-23 21:00:00',
  week: 13,
  weekDay: 'SEG',
},
{
  category: 'A',
  round: 24,
  teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
  scoreAway: '',
  day: '2020-03-24 21:00:00',
  week: 13,
  weekDay: 'TER',
},
{
  category: 'A',
  round: 24,
  teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
  scoreAway: '',
  day: '2020-03-25 21:00:00',
  week: 13,
  weekDay: 'QUA',
},
{
  category: 'A',
  round: 24,
  teamHome: teams.find((team) => team.longName === 'PARMA')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'MILAN')._id,
  scoreAway: '',
  day: '2020-03-26 21:00:00',
  week: 13,
  weekDay: 'QUI',
},
{
  category: 'A',
  round: 24,
  teamHome: teams.find((team) => team.longName === 'ROMA')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
  scoreAway: '',
  day: '2020-03-30 21:00:00',
  week: 14,
  weekDay: 'SEG',
},
// ROUND 25
{
  category: 'A',
  round: 25,
  teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'MILAN')._id,
  scoreAway: '',
  day: '2020-03-31 21:00:00',
  week: 14,
  weekDay: 'TER',
},
{
  category: 'A',
  round: 25,
  teamHome: teams.find((team) => team.longName === 'SASSUOLO')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'JUVENTUS')._id,
  scoreAway: '',
  day: '2020-04-01 21:00:00',
  week: 14,
  weekDay: 'QUA',
},
{
  category: 'A',
  round: 25,
  teamHome: teams.find((team) => team.longName === 'SAMPDORIA')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
  scoreAway: '',
  day: '2020-04-02 21:00:00',
  week: 14,
  weekDay: 'QUI',
},
{
  category: 'A',
  round: 25,
  teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
  scoreAway: '',
  day: '2020-04-06 21:00:00',
  week: 15,
  weekDay: 'SEG',
},
{
  category: 'A',
  round: 25,
  teamHome: teams.find((team) => team.longName === 'ROMA')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'PARMA')._id,
  scoreAway: '',
  day: '2020-04-07 21:00:00',
  week: 15,
  weekDay: 'TER',
},
// ROUND 26
{
  category: 'A',
  round: 26,
  teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'MILAN')._id,
  scoreAway: '',
  day: '2020-04-08 21:00:00',
  week: 15,
  weekDay: 'QUA',
},
{
  category: 'A',
  round: 26,
  teamHome: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
  scoreAway: '',
  day: '2020-04-09 21:00:00',
  week: 15,
  weekDay: 'QUI',
},
{
  category: 'A',
  round: 26,
  teamHome: teams.find((team) => team.longName === 'PALERMO')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
  scoreAway: '',
  day: '2020-04-13 21:00:00',
  week: 16,
  weekDay: 'SEG',
},
{
  category: 'A',
  round: 26,
  teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'ROMA')._id,
  scoreAway: '',
  day: '2020-04-14 21:00:00',
  week: 16,
  weekDay: 'TER',
},
{
  category: 'A',
  round: 26,
  teamHome: teams.find((team) => team.longName === 'PARMA')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'FIORENTINA')._id,
  scoreAway: '',
  day: '2020-04-15 21:00:00',
  week: 16,
  weekDay: 'QUA',
},
// ROUND 27
{
  category: 'A',
  round: 27,
  teamHome: teams.find((team) => team.longName === 'JUVENTUS')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'INTERNAZIONALE')._id,
  scoreAway: '',
  day: '2020-04-16 21:00:00',
  week: 16,
  weekDay: 'QUI',
},
{
  category: 'A',
  round: 27,
  teamHome: teams.find((team) => team.longName === 'MILAN')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'ROMA')._id,
  scoreAway: '',
  day: '2020-04-27 21:00:00',
  week: 18,
  weekDay: 'SEG',
},
{
  category: 'A',
  round: 27,
  teamHome: teams.find((team) => team.longName === 'FIORENTINA')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'SASSUOLO')._id,
  scoreAway: '',
  day: '2020-04-28 21:00:00',
  week: 18,
  weekDay: 'TER',
},
{
  category: 'A',
  round: 27,
  teamHome: teams.find((team) => team.longName === 'NAPOLI')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'SAMPDORIA')._id,
  scoreAway: '',
  day: '2020-04-29 21:00:00',
  week: 18,
  weekDay: 'QUA',
},
{
  category: 'A',
  round: 27,
  teamHome: teams.find((team) => team.longName === 'PARMA')._id,
  scoreHome: '',
  teamAway: teams.find((team) => team.longName === 'PALERMO')._id,
  scoreAway: '',
  day: '2020-04-30 21:00:00',
  week: 18,
  weekDay: 'QUI',
},
